# Homieflow configuration

# Server network configuration
# [network]
# address = "127.0.0.1" # Change to 0.0.0.0 to allow clients from other networks to connect
# base-url = "http://localhost:6001" # Set this to the public URL used for your server.

# Secret values for server.
# [secrets]
# refresh-key =
# access-key =
# authorization-code-key =

# TLS/SSL Configuration. If not defined, TLS will be disabled. 
# [tls]
# certificate =   # e.g /etc/letsencrypt/live/example.com/fullchain.pem
# private-key =   # e.g /etc/letsencrypt/live/example.com/privkey.pem

# Google provider configuration. If not defined, Google Home integration will be disabled.
# [google]
# client-id =     # Actions Console -> Account Linking -> Client ID.
# client-secret = # Actions Console -> Account Linking -> Client Secret. 
# project-id =    # Project ID set during creation.
# credentials-file = # JSON service account credentials file downloaded from Google, for gRPC API.

# Google login configuration. If not defined, Google login will be disabled.
# [logins.google]
# client-id =     # Client ID assigned by Google.


# Define a new structure.
# [[structures]]
# id =            # Unique 16 byte hex-encoded structure identifier.
# name =          # Name of the structure. 

# Define a new room.
# [[rooms]]
# id =            # Unique 16 byte hex-encoded room identifier.
# structure-id =  # 16 byte hex-encoded room identifier, must reference to an existing structure.
# name =          # Name of the room.

# Define a new permission.
# [[permissions]]
# structure-id =  # 16 byte hex-encoded room identifier, must reference to an existing structure.
# user-id =  # 16 byte hex-encoded user identifier, must reference to an existing user.
# is-manager = # True if user can manage structure(add new devices, invite new home members).
