[network]
address = "0.0.0.0"
port = 1234
base-url = "http://localhost:1234"

[secrets]
refresh-key = "${REFRESH_KEY}"
access-key = "${ACCESS_KEY}"
authorization-code-key = "${AUTHORIZATION_CODE_KEY}"

[tls]
certificate = "/etc/certificate"
private-key = "/etc/private-key"
address = "1.2.3.4"
port = 4321

[google]
client-id = "google-client-id"
client-secret = "google-client-secret"
project-id = "google-project-id"
credentials-file = "google-credentials.json"

[logins.google]
client-id = "google-login-client-id"

[[structures]]
id = "bd7feab5033940e296ed7fcdc700ba65"
name = "Zukago"

[[rooms]]
id = "baafebaa0708441782cf17470dd98392"
structure-id = "bd7feab5033940e296ed7fcdc700ba65"
name = "Bedroom"

[[users]]
id = "861ccceaa3e349138ce2498768dbfe09"
email = "root@gbaranski.com"

[[permissions]]
structure-id = "bd7feab5033940e296ed7fcdc700ba65"
user-id = "861ccceaa3e349138ce2498768dbfe09"
is-manager = true
